blog/urls.py
# from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
	# path(r'^$',views.index,name='blog_index'),
	url(r'^$', views.index,name='blog_index'),
	url(r'^(?P<blog_id>[0-9]+)',views.detail,name='blog_detail'),
	url(r'^category/(?P<category_id>[0-9]+)/$',views.catagory,name='blog_category'),
	url(r'^tag/(?P<tag_id>[0-9]+)/$',views.tag,name='blog_tag'),
	url(r'^search/$', views.search,name='blog_search'),
	url(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',views.archives,name='blog_archives'),
	url(r'^reply/(?P<comment_id>\d+)/$', views.reply, name='comment_reply'),
]

djangoBlog/urls.py
from django.contrib import admin
# 路由系统：旧django.conf.urls，新django.urls
from django.conf.urls import url,include

from django.conf import settings
from django.conf.urls.static import static

from blog.feed import LatestEntriesFeed

from blog import views as blog_views

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry

info_dict = {
    'queryset': Entry.objects.all(),
    'date_field': 'modifyed_time'
}

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^login/$', blog_views.login),
    url(r'^logout/$', blog_views.logout),
    url(r'^latest/feed/$', LatestEntriesFeed()),    #RSS订阅
    # 如果sitemap.xml位于根目录中，它会引用网站中的任何URL。 但是如果站点地图位于/content/sitemap.xml，则它只能引用以/content/开头的网址。
    # 使用GenericSitemap构造一个GenericSitemap类型的数据，priority为更新频率0-1之间
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
      name='django.contrib.sitemaps.views.sitemap'),       #站点地图
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT ) #添加图片的url


# 需要DEBUG = False
handler403 = blog_views.permission_denied
handler404 = blog_views.page_not_found
handler500 = blog_views.page_error

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse


# 文章分类
class Category(models.Model):
  # verbose_nam='分类'可以简写为'分类'
  name = models.CharField('分类',max_length=128)

  def __str__(self):
    return self.name
  
  # 后台管理展示定制
  class Meta:
    # 给模型起个中文名字
    verbose_name = '博客分类'
    # verbose_name的复数形式，默认在后面加上's'
    verbose_name_plural = verbose_name


# 标签
class Tag(models.Model):
  name = models.CharField('标签',max_length=128)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name = '博客标签'
    verbose_name_plural = verbose_name


# 文章
class Entry(models.Model):
  title = models.CharField('文章标题',max_length=128)
  # 外键可以是一个模型类
  author = models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE)
  img = models.ImageField(upload_to='blog_img',null=True,blank=True,verbose_name='博客配图')
  body = models.TextField('正文',)
  abstract = models.TextField('摘要',max_length=256,null=True,blank=True)
  # 外键也可以是一个模型名
  visiting = models.PositiveIntegerField('访问量',default=0)
  category = models.ManyToManyField('Category',verbose_name='博客分类')
  tags = models.ManyToManyField('Tag',verbose_name='标签')
  # auto_now_add：为添加时的时间，修改对象不会变动
  created_time = models.DateTimeField('创建时间',auto_now_add=True)
  # auto_now：添加或修改对象，会更新时间
  modifyed_time = models.DateTimeField('修改时间',auto_now=True)

  def __str__(self):
    return self.title
  
  # 获取详情页地址（自定义方法）
  def get_absolute_url(self):
    return reverse('blog:blog_detail',kwargs={'blog_id':self.id})

  # 更新访问量（自定义方法）
  def increase_visiting(self):
    self.visiting += 1
    # update_fields：要保存的字段
    self.save(update_fields=['visiting'])
      
  class Meta:
    ordering = ['-created_time']
    verbose_name = '博客正文'
    verbose_name_plural = verbose_name
    

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect

from . import models
from django.db.models import Q

import markdown, pygments

# https://www.cnblogs.com/kongzhagen/p/6640975.html
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# https://www.cnblogs.com/feixuelove1009/p/8000556.html
# blog应用用到django_comments应用的评论数据
from django_comments.models import Comment
from django_comments import models as comment_models

import requests
import json
from django.conf import settings
# Create your views here.

# 返回当前page页的数据，和一个实例paginator
def make_paginator(objects,page,num=3):
	paginator = Paginator(objects,num)
	try:
		object_list = paginator.page(page)
	except PageNotAnInteger:
		object_list = paginator.page(1)
	except EmptyPage:
		object_list = paginator.page(paginator.num_pages)
	
	return object_list,paginator



# 通过传入实例paginator和当前page页,返回一个自定义分页页码（字典）
def pagination_data(paginator, page):
	if paginator.num_pages == 1:
		# 如果无法分页
		return {}
	# 当前页左边连续的页码号，初始值为空
	left = []
	right = []

	# 标示第 1 页页码后是否需要显示省略号
	left_has_more = False
	right_has_more = False

	# 标示是否需要显示第 1 页的页码号。
	# 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
	# 其它情况下第一页的页码是始终需要显示的。
	# 初始值为 False
	first = False

	# 标示是否需要显示最后一页的页码号。
	# 需要此指示变量的理由和上面相同。
	last = False

	# 获得用户当前请求的页码号
	try:
		page_number = int(page)
	except ValueError:
		page_number = 1
	except:
		page_number = 1

	total_pages = paginator.num_pages
	page_range = paginator.page_range

	if page_number == 1:
		# 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
		# 此时只要获取当前页右边的连续页码号，
		# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
		# 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
		right = page_range[page_number:page_number + 4]

		# 如果最右边的页码号比最后一页的页码号减去 1 还要小，
		# 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
		if right[-1] < total_pages - 1:
			right_has_more = True

		# 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
		# 所以需要显示最后一页的页码号，通过 last 来指示
		if right[-1] < total_pages:
			last = True

	elif page_number == total_pages:
		# 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
		# 此时只要获取当前页左边的连续页码号。
		# 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
		# 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
		left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

		# 如果最左边的页码号比第 2 页页码号还大，
		# 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
		if left[0] > 2:
			left_has_more = True

		# 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
		# 所以需要显示第一页的页码号，通过 first 来指示
		if left[0] > 1:
			first = True
	else:
		# 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
		# 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
		left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
		right = page_range[page_number:page_number + 2]

		# 是否需要显示最后一页和最后一页前的省略号
		if right[-1] < total_pages - 1:
			right_has_more = True
		if right[-1] < total_pages:
			last = True

		# 是否需要显示第 1 页和第 1 页后的省略号
		if left[0] > 2:
			left_has_more = True
		if left[0] > 1:
			first = True

	data = {
		'left': left,
		'right': right,
		'left_has_more': left_has_more,
		'right_has_more': right_has_more,
		'first': first,
		'last': last,
	}
	return data



def index(request):
	entries = models.Entry.objects.all()
	page = request.GET.get('page',1)
	entry_list, paginator = make_paginator(entries, page)
	page_data = pagination_data(paginator, page)

	# locals()返回一个包含当前作用域里面的所有变量和它们的值的字典
	return render(request,'blog/index.html',locals())


def detail(request,blog_id):
	# entry = models.Entry.objects.get(id=blog_id)
	# 查找不到文章跳转到404页面
	entry = get_object_or_404(models.Entry,id=blog_id)
	entry.increase_visiting()

	md = markdown.Markdown(extensions=[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc',
	])
	entry.body = md.convert(entry.body)
	entry.toc = md.toc

	comment_list = list()

	# 参数为最顶层的评论
	def get_comment_list(comments):
		for comment in comments:
			# 加入最顶层的评论
			comment_list.append(comment)
			children = comment.child_comment.all()
			# 一直获取子评论，直到没有子评论
			if len(children) > 0:
				get_comment_list(children)

	top_comments = Comment.objects.filter(object_pk=blog_id, parent_comment=None,
																				content_type__app_label='blog').order_by('-submit_date')
	get_comment_list(top_comments)

	return render(request,'blog/detail.html',locals())



def catagory(request,category_id):
	c = get_object_or_404(models.Category,id=category_id)
	entries = models.Entry.objects.filter(category=c)

	page = request.GET.get('page',1)
	entry_list, paginator = make_paginator(entries, page)
	page_data = pagination_data(paginator, page)

	# 和index()用到的模板是一样的
	return render(request, 'blog/index.html', locals())


def tag(request,tag_id):
	t = get_object_or_404(models.Tag,id=tag_id)
	if t.name == "全部":
			entries = models.Entry.objects.all()
	else:
			entries = models.Entry.objects.filter(tags=t)
	page = request.GET.get('page', 1)
	entry_list, paginator = make_paginator(entries, page)
	page_data = pagination_data(paginator, page)

	return render(request, 'blog/index.html', locals())



def search(request):
	# 如果是post请求，需要在模板表单里加入csrf_token
	keyword = request.GET.get('keyword',None)
	if not keyword:
		error_msg = '请输入关键字'
		return render(request,'blog/index.html',locals())

	# 从标题、正文、摘要里面查找关键字，获取包含关键字的文章
	entries = models.Entry.objects.filter(Q(title__icontains=keyword)
																				| Q(body__icontains=keyword)
																				| Q(abstract__icontains=keyword))
	# 数据的显示和index()方式一致
	page = request.GET.get('page', 1)
	entry_list, paginator = make_paginator(entries, page)
	page_data = pagination_data(paginator, page)

	return render(request, 'blog/index.html', locals())



def archives(request,year,month):
	entries = models.Entry.objects.filter(created_time__year=year,created_time__month=month)
	page = request.GET.get('page',1)
	entry_list,paginator = make_paginator(entries,page)
	page_data = pagination_data(paginator,page)

	return render(request,'blog/index.html',locals())



def reply(request,comment_id):
	# https://www.cnblogs.com/gyh04541/p/7985968.html
	if not request.session.get('login', None) and not request.user.is_authenticated:
		return redirect('/')

	parent_comment = get_object_or_404(comment_models.Comment, id=comment_id)

	return render(request, 'blog/reply.html', locals())



def permission_denied(request):
	'''403'''
	return render(request, 'blog/403.html', locals())


def page_not_found(request):
	'''404'''
	return render(request, 'blog/404.html', locals())


def page_error(request):
	'''500'''
	return render(request, 'blog/500.html', locals())



def login(request):
	# 先拿到授权code
	code = request.GET.get('code', None)
	if code is None:
		return redirect('/')
	
	access_token_url = 'https://api.weibo.com/oauth2/access_token?client_id=%s&client_secret=%s&grant_type=authorization_code&redirect_uri=http://127.0.0.1:8000/login&code=%s'\
                        %(settings.CLIENT_ID, settings.APP_SECRET, code)
	ret = requests.post(access_token_url)

	data = ret.text    #微博返回的数据是json格式的
	data_dict = json.loads(data)   #转换成python字典格式
	token = data_dict['access_token'] #通过code换取token，用于请求认证
	uid = data_dict['uid']  # 通过unionID，可以拿到微博用户的基本信息

	request.session['token'] = token
	request.session['uid'] = uid
	request.session['login'] = True

	#获取微博用户的信息
	user_info_url = 'https://api.weibo.com/2/users/show.json?access_token=%s&uid=%s' % (token, uid)
	user_info = requests.get(user_info_url)
	user_info_dict = json.loads(user_info.text)

	request.session['screen_name'] = user_info_dict['screen_name']
	request.session['profile_image_url'] = user_info_dict['profile_image_url']

	return redirect(request.GET.get('next', '/'))



def logout(request):
	if request.session['login']:
		del request.session['login']
		del request.session['uid']
		del request.session['token']
		del request.session['screen_name']
		del request.session['profile_image_url']
		return redirect(request.Get.get('next', '/'))
	else:
		return redirect('/')

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/blog_nav.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/back-to-top.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="my-nav">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/blog/">博客</a></li>
        <li><a href="#">学习资源</a></li>
        <li><a href="#">联系我</a></li>
      </ul>

      <!-- action地址对应blog_search路由 -->
      <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="keyword">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
          {% if request.session.login %}
              <li>{{ request.session.screen_name }}<a href="/logout/?next={{ request.path }}">
                  <i class="glyphicon glyphicon-log-out"></i>注销
                </a>
              </li>
          {% else %}
              <li>
                  <a href="https://api.weibo.com/oauth2/authorize?client_id=2241881638&response_type=code&redirect_uri=http://127.0.0.1:8000/login/?next={{ request.path }}">
                      <i class="glyphicon glyphicon-log-in"></i>&nbsp;&nbsp;登录
                  </a>
              </li>
          {% endif %}
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}

<div id="back-to-top">
    <i class="glyphicon glyphicon-arrow-up"></i>
</div>

 <footer>
    <div class="footer" role="navigation">
        <div class="container">
            <div class="navbar-text">
                <ul class="footer-text">
                    <li><a href="#">主页</a></li>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">关于博主</a></li>
                    <li><a href="#">文档支持</a></li>
                    <li><a href="/blog/">博客首页</a></li>
                </ul>
                <p>Copyright © 2018 </p>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script>
    $("#back-to-top").click(function () {
        window.scrollTo(0,0);
    });
</script>
{% block script %}{% endblock %}

</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block title %}博客详情页{% endblock %}

{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/github.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/blog_comment.css' %}">
{% endblock %}

{% load comments %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{{ entry.title }}</h1>
                <p>
                    <strong>{{ entry.author }}</strong>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日' }}
                    &nbsp;&nbsp;&nbsp;&nbsp;分类：
                    {% for category in entry.category.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                    {% endfor %}

                    &nbsp;&nbsp;&nbsp;&nbsp;标签：
                    {% for tag in entry.tags.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}

                    &nbsp;&nbsp;&nbsp;&nbsp;浏览量：
                    &nbsp;&nbsp;{{ entry.visiting }}

                    {% if entry.img %}
                        <img src="{{ entry.img.url }}" width="60%" height="270px"/>
                    {% endif %}
                    <hr />
                    <p>
                        {{ entry.toc|safe }}
                        {{ entry.body|safe }}
                    </p>
                </p>
            </div>
            <div class="col-md-3">
                <!-- 除了extends，include也可以定义block -->
                {% block toc %}
                    <div class="row">
                        <div class="widget">
                            <h3>博客目录</h3>
                            {{ entry.toc|safe }}
                        </div>
                    </div>
                {% endblock %}
                {% include 'blog/right_site_bar.html' %}
            </div>
        </div>

        <div class="row">
            <hr />
            {% get_comment_form for entry as form %}
            {% get_comment_count for entry  as comment_count %}
            <h3 >评论总数： {{ comment_count }}</h3>
            <hr />
        </div>

        {#评论表单#}
        {% if request.session.login or request.user.is_authenticated %}
            <div class="row">
                <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="input_title" class="pull-left control-label">评论标题：</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_comment" class="pull-left control-label">评论内容:</label>
                        <div class="col-sm-6">
                        <textarea style="resize:none;" class="form-control" rows=6 name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                        </div>
                    </div>
                    <!-- honeypot域。这是一个陷阱，如果该域被填入任何数据，那么该评论会被拒绝提交。因为垃圾发送者往往自动的为表单的所有域填入一定数据，视图制造一个合法合格的提交数据单。 -->
                    <span style="display: none;">{{ form.honeypot }}</span>
                    <!-- 如果使用自定义的form，请确保这些字段原样的被引用。 -->
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    <!-- 时间戳用于确保“回复攻击”不会持续太久时间。那些在请求表单和提交表单时间差过长的用户，将被拒绝提交评论。 -->
                    {{ form.timestamp }}
                    <!-- 用于验证信息的安全哈希 -->
                    {{ form.security_hash }}
                    <!-- 用户评论后将页面重定向到另外一个地址 -->
                    <input type="hidden" name="next" value="{% url 'blog:blog_detail' entry.id %}" />
                    <input  name="parent_id" type="hidden" value="-1" />
                    <input  name="level" type="hidden" value="0" />

                    <div class="form-group col-sm-7">
                        <div class="pull-left" style="margin-left: 68px;">
                            <button type="reset"  class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                        </div>
                        <div class="pull-right" style="margin-right: 12px;">
                            <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;评论</button>
                        </div>
                    </div>
                </form>
            </div>
        {% else %}
            <h3>登陆后才可以评论</h3>
        {% endif %}


        {#评论显示区#}
        <div class="row">
        {% for comment in comment_list %}
            <div class="single_comment" style="margin-left: {{ comment.level }}em">
                <div>
                    {% if comment.user_img %}
                        <img src="{{ comment.user_img }}" alt="user_image" />
                    {% else %}
                        <img src="{% static 'blog/images/cl.jpg' %}" />
                    {% endif %}
                </div>
                <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                    <strong>{{ comment.comment_title }}</strong>
                    <div>
                        {% if comment.parent_comment %}
                                    {{ comment.user_name }}{{ request.user }}
                                    <i class="glyphicon glyphicon-share-alt"></i>
                                    {{ comment.parent_comment.user_name }}{{ request.user }}
                        {% else %}
                                By&nbsp;&nbsp;
                                    {{ comment.user_name }}{{ request.user }}
                                &nbsp;&nbsp;&nbsp;On&nbsp;&nbsp;
                        {% endif %}
                        <em>{{ comment.submit_date }}</em>
                        {% if request.session.login or request.user.is_authenticated %}
                        &nbsp;&nbsp;&nbsp;<a href="{% url 'blog:comment_reply' comment.id %}">回复</a>
                        {% endif %}
                    </div>
                <br />
                    <p>{{ comment.comment }}</p>
                </div>
            </div>
        {% endfor %}
        </div>

    </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}博客首页{% endblock %}

{% block content %}

    <div class="container">
        <!-- 内容列表 -->
        <div class="row">
            <div class="col-md-9">
                {% for entry in entry_list %}
                    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2> <br>
                    {% if entry.img %}
                        <img src="{{ entry.img.url }}" width="60%" height="270px"/>
                    {% endif %}
                    {% if entry.abstract %}
                        <p>{{ entry.abstract }}</p>
                    {% else %}
                        <p>{{ entry.body|truncatechars:180 }}</p>
                    {% endif %}
                    <p>
                        <span>作者：{{ entry.author }}</span>
                        <span>&nbsp;&nbsp;&nbsp;&nbsp;发布时间：{{ entry.created_time }}</span>
                        <span>&nbsp;&nbsp;&nbsp;&nbsp;阅读数：{{ entry.visiting }}</span>
                    </p>
                {% endfor %}
            </div>
            <div class="col-md-3">
                {% include 'blog/right_site_bar.html' %}
            </div>
        </div>
        <!-- 分页 -->
        <div id="paginator" class="pull-right">
                <ul class="pagination">
                    {% if entry_list.has_previous %}
                        <li><a href="?page={{ entry_list.previous_page_number }}"><i
                                class="glyphicon glyphicon-chevron-left"></i>前一页</a></li>
                    {% endif %}

                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}

                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}

                        {% for i in left %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}

                    <li class="active"><a href="?page={{ entry_list.number }}">{{ entry_list.number }}</a></li>

                    {% if right %}
                        {% for i in right %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}

                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}

                    {% if last %}
                        <li><a href="?page={{ entry_list.num_pages }}">{{ entry_list.num_pages }}</a></li>
                    {% endif %}

                    {% if entry_list.has_next %}
                        <li><a href="?page={{ entry_list.next_page_number }}">下一页<i
                                class="glyphicon glyphicon-chevron-right"></i></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/right_site_bar.html
<!-- 在使用自定义过滤器和自定义标签时，要导入blog_tags.py -->
{% load blog_tags %}

{% block toc %}{% endblock %}

<div class="row">
    <div class="widget">
        <h3>最新博客</h3>
        <!-- 自定义标签不能直接用到if和for里面 -->
        {% get_recent_entries as recent_entry_list %}

        {% for entry in recent_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <div>{{ entry.author }}   发表于：{{ entry.created_time|date:"Y年m月d日" }}</div>
            </div>
        {% endfor %}
    </div>
</div>


<div class="row">
    <div class="widget">
        <h3>推荐博客</h3>
        {% get_popular_entries as popular_entry_list %}

        {% for entry in popular_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <span class="badge" style="color: white;background-color: darkgreen">{{ entry.visiting }}</span>
            </div>
        {% endfor %}
    </div>
</div>


<div class="row">
    <div class="widget">
        <h3>分类:</h3>
        {% get_categories as category_list %}
        <ul class="list-group">
        {% for category in category_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                <!-- 自定义标签的参数直接跟在后面 -->
                <span class="badge">{% get_entry_count_of_category category.name %}</span>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>


<div class="row">
    <div class="widget">
        <h3>归档:</h3>
        {% archives as date_list %}
        <ul class="list-group">
        {% for date in date_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_archives' date.year date.month %}">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                    {{ date.year }} 年 {{ date.month }} 月
                    <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                </a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>


<div class="row">
    <div class="widget">
        <h3>标签云:</h3>
        {% get_tags as tag_list %}
        {% for tag in tag_list %}
            <a href="{% url 'blog:blog_tag' tag.id %}" style="font-size: 20px;">
                <span style="padding: 5px;" class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}">{{ tag.name }}</span>
            </a>&nbsp;
        {% endfor %}
    </div>
</div>


<div class="row" style="margin-top: 30px">
    <div class="rss">
        <a href="/latest/feed/"><i class="glyphicon glyphicon-plus"></i>RSS 订阅</a>
    </div>
</div>
 